# fly.toml app configuration file generated for datcord on 2024-12-05T02:28:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'datcord'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[[services]]
  protocol = "tcp"
  internal_port = 3000

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = "80"
    handlers = ["http"]

  [[services.ports]]
    port = "443"
    handlers = ["tls", "http"]
    force_https = true

  [services.tcp_checks]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"

[metrics]
  port = 9091
  path = "/metrics"