app = 'datcord'
primary_region = "iad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  PORT = "3000"

[metrics]
  port = 9091
  path = "/metrics"